/** @format */

import Link from "next/link";
import React, { useState } from "react";
import { Form } from "react-bootstrap";

const Policy = () => {
	const [policy, setPolicy] = useState(null);

	const handleChangePolicy = (selectedPolicy) => {
		setPolicy(selectedPolicy);
	};

	return (
		<section className="layout_Policy-components px-lg-0 px-4">
			<div className="row">

				<div className="col-lg-12 text-center d-lg-block d-none">
					<img src="../../assets/image/logo.svg" className="iconlogo_reg" />
					<img src="../../assets/image/JNFT_LOGO.svg" className="iconlogo_JKNFT" />
					<h2 className="txt-set-detail-JNFT mt-4">ข้อตกลง และเงื่อนไขสิทธิในการครอบครอง และการนำไปใช้</h2>
				</div>
				<div className="col-lg-12 text-center mb-4 d-block d-lg-none">
					<img src="../../assets/image/logo.svg" className="iconlogo_reg" />
				</div>
				<div className="col-lg-12 text-center d-block d-lg-none">
					<img src="../../assets/image/JNFT_LOGO.svg" className="iconlogo_JKNFT" />
				</div>
				<div className="col-12 text-center d-block d-lg-none">
					<h2 className="txt-set-detail-JNFT mt-4">ข้อตกลง และเงื่อนไขสิทธิในการครอบครอง และการนำไปใช้</h2>
				</div>

			</div>
			<div className="row d-flex justify-content-center field-group">
				<div className="col-12 col-lg-7 ">
					<div className="box-policy-scroll">
						NFT ที่ทางไปรษณีย์ไทย ได้สร้างสรรค์ขึ้นมา เป็นการมอบให้ฟรีที่มูลค่าของ NFT ชิ้นนั้น แต่ในการรับ NFT
						ลูกค้าจำเป็นต้องเชื่อมต่อกระเป๋าสินทรัพย์ดิจิทัล เพื่อบันทึก NFT นั้น ทั้งนี้ ในการรับ NFT จะไม่มีค่าธรรมเนียมใดๆเกิดขึ้น
						โดยค่าธรรมเนียมเหล่านี้ ทางไปรษณีย์ไทย เป็นผู้รับผิดชอบทั้งสิ้น เนื่องจาก NFT เป็นสินทรัพย์ดิจิตัลบนระบบบล็อกเชน ที่เมื่อบันทึกลงไปแล้ว
						จะไม่มีผู้ใดสามารถดัดแปลง หรือแก้ไขได้ รวมถึงทางไปรษณีย์ไทย ศิลปินผู้สร้างผลงาน และผู้ครอบครองชิ้นงานนั้นๆ เองด้วย
						จึงขอสงวนสิทธิ์ไม่แก้ไขข้อมูลต่างๆ ไฟล์ภาพ หรือลบออกจากระบบ ในทุกๆ กรณี NFT ทุกชิ้น ถูกสร้างโดยการผสมผสานภาพชิ้นส่วนต่างๆ
						ขึ้นมาโดยโปรแกรมในระบบสุ่ม เพื่อให้ 50,000 ชิ้นออกมาไม่เหมือนกัน NFT เป็นชิ้นงานศิลปะเพื่อการสะสม และอยู่ในรูปแบบ NFT จริง
						บนบล็อกเชนที่ชื่อว่า JNFT โดยผู้ครอบครองสามารถนำไปขายต่อในตลาด NFT บนบล็อกเชนเดียวกันได้ แต่ไม่สามารถนำมาแลกเปลี่ยนเป็นเงินสดได้ NFT
						ยังถือเป็นลิขสิทธิ์คาแร็คเตอร์ของ ไปรษณีย์ไทย ผู้สร้างสรรค์ผลงาน โดยผู้ครอบครอง แสตมป์ NFT ไม่สามารถนำไปจัดพิมพ์ ผลิตเป็นสินค้า ทำซ้ำ
						ดัดแปลง หรือนำไปใช้เพื่อการค้าในรูปแบบอื่น นอกเหนือจากการขายโอนกรรมสิทธิ์ในรูปแบบ NFT ผ่าน NFT Market เท่านั้น ผู้ครอบครอง NFT
						สามารถเซฟไฟล์ภาพออกมาเพื่อใช้ในการแสดงออกในการครอบครองใน Social Networks ได้ เช่น นำไปเป็นภาพ Profile Picture, โพสต์บนสื่อโซเชียล
						หรืออินเตอร์เน็ต แต่ไม่อนุญาตให้ทำการดัดแปลง หรือเผยแพร่ในช่องทางสื่อสาธารณะ อาทิ ใบปลิว, TV, ป้ายขนาดใหญ่, Digital Signage
					</div>
					<div className="box-policy-scroll">
					JNFT Term and Conditions<br/>
1. Introduction
Welcome to the JVC website, owned and operated by J Ventures Co., Ltd. c. d/b/a JVC (“JVC,” “we,” “us” or “our”). These Terms of Use (these “Terms”) govern your access to and use of the JVC website; including without limitation the creation, purchase, sale, exchange, or modification of certain digital assets; our online and/or mobile services, and software provided on or in connection with those services (collectively, the “Service”, or JNFT).
What is JNFT?
JNFT (the “Platform”) is a platform for artists, corporate or anyone (“Creators”) and collectors (“Collectors”) to sell, purchase, list for auction, make offers, and bid (each a “Transaction”) on digital art  (“Digital Artwork”) represented on a non-fungible tokens based on Binance Smart Chain (BEP-20) and may scale to other blockchain in the future.  
Smart-Contract Enabled.  The Digital Artwork on JNFT is represented on smart contracts on the blockchain that provides an immutable ledger of all transactions that occur on JNFT (“Smart Contracts”).  This means that all Digital Artwork is outside of the control of any one party, including JNFT, and is subject to many risks and uncertainties.  We neither own nor control MetaMask, Digital Asset Exchanges, the Binance Smart Chain network, your browser, or any other third party site, product, or service that you might access, visit, or use for the purpose of enabling you to use the various features of the Platform. We will not be liable for the acts or omissions of any such third parties, nor will we be liable for any damage that you may suffer as a result of your transactions or any other interaction with any such third parties.  The User understands that your Binance Smart Chain public address will be made publicly visible whenever you engage in a transaction on the Platform. 
Noncustodial.  While JNFT offers a marketplace for Digital Artwork, it does not buy, sell, or ever take custody or possession of any Digital Artwork. The Platform facilitates User collection of Digital Artwork, but neither JVC nor JNFT are custodians of any Digital Artwork.  The User understands and acknowledges that the Smart Contracts do not give JVC nor JNFT custody, possession, or control of any Digital Artwork or cryptocurrency at any time for the purpose of facilitating transactions on the Platform.  You affirm that you are aware and acknowledge that JNFT is a non-custodial service provider and has designed this Platform to be directly accessible by the Users without any involvement or actions taken by JNFT or any third-party.  As a marketplace, JNFT cannot make any representation or guarantee that Creators will achieve any particular outcome as the result of listing their Digital Artwork on JNFT. 
How do I use JNFT?
Your Registration Obligations:  Anyone can browse JNFT without registering for an account. You may be required to register with JNFT in order to access and use certain features on the Platform, such as participating as a Creator or Collector.  If you choose to register for the Platform, you agree to provide and maintain true, accurate, current, and complete information about yourself as prompted by our registration form.  Registration data and certain other information about you are governed by our Privacy Policy.  There is no age restriction in order to register for an account as a Creator, but you must be at least completely 20 years old to register for an account as a Collector or a buyer depending on your jurisdiction i.e. Sui Juris to place a bid on any Digital Artwork. If you are under or not completely 20 years old, you must have the expressed permission of a parent or legal guardian who can accept these Terms on your behalf. You are responsible for anything that occurs when anyone is signed in to your account, as well as the security of the account.
Member Account, Password, and Security: You are responsible for maintaining the confidentiality of your account and password, if any, and are fully responsible for any and all activities that occur under your password or account.  You agree to (a) immediately notify JNFT of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session when accessing JNFT.  JNFT will not be liable for any loss or damage arising from your failure to comply with this Section.
Modifications to the Platform: JNFT reserves the right to modify or discontinue, temporarily or permanently, the Platform (or any part thereof) with or without notice.  You agree that JNFT will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Platform.

This Service or JNFT also allows you to sell and purchase Digital Assets (as defined below) via auction (“Auction”). Detailed rules regarding the Auction process are available on this page, Auction Rules. You may only participate in the Auction by linking your digital wallets on supported bridge extensions such as MetaMask (https://metamask.io/). MetaMask is an electronic wallet, which allows you to purchase, store, and engage in transactions using Binance Coin and Binance Smart Chain based cryptocurrencies. Before putting up your unique digital asset for Auction or putting in an offer to purchase a unique digital asset from another user, we will ask you to download a supported electronic wallet extension, and connect and unlock your digital wallets with that extension. Once you submit an order to sell or purchase a unique digital asset, your order is passed on to the applicable extension, which completes the transaction on your behalf.
“Digital Assets” refers to Digital Artworks represented by unique non-fungible tokens, implemented on the Blockchain using smart contracts.

ALL TRANSACTIONS INITIATED THROUGH OUR SERVICE ARE FACILITATED AND RUN BY THIRD-PARTY ELECTRONIC WALLET EXTENSIONS, AND BY USING OUR SERVICES YOU AGREE THAT YOU ARE GOVERNED BY THE TERMS OF SERVICE AND PRIVACY POLICY FOR THE APPLICABLE EXTENSIONS. FOR METAMASK, THOSE TERMS ARE AVAILABLE AT (https://jnft.digital)

JVC IS A PLATFORM. WE ARE NOT A BROKER, FINANCIAL INSTITUTION, OR CREDITOR. THE SERVICES ARE AN ADMINISTRATIVE PLATFORM ONLY. JVC FACILITATES TRANSACTIONS BETWEEN THE BUYER AND SELLER IN THE AUCTION BUT IS NOT A PARTY TO ANY AGREEMENT BETWEEN THE BUYER AND SELLER OF DIGITAL ASSETS OR BETWEEN ANY USERS.

YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE IDENTITY, LEGITIMACY, AND AUTHENTICITY OF ASSETS YOU PURCHASE ON JVC. NOTWITHSTANDING INDICATORS AND MESSAGES THAT SUGGEST VERIFICATION, JVC MAKES NO CLAIMS ABOUT THE IDENTITY, LEGITIMACY, OR AUTHENTICITY OF ASSETS ON THE PLATFORM.

Because we have a growing number of services, we sometimes need to describe additional terms for specific services. Those additional terms and conditions, which are available with the relevant services, then become part of your agreement with us if you use those services.

THESE TERMS OF USE ARE IMPORTANT AND AFFECT YOUR LEGAL RIGHTS, SO PLEASE READ THEM CAREFULLY. WE WANT TO LET YOU KNOW THAT THE TERMS INCLUDE AN ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION. UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT: (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AND SEEK RELIEF AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING; AND (2) YOU ARE AGREEING TO MANDATORY INDIVIDUAL ARBITRATION FOR THE RESOLUTION OF DISPUTES AND WAIVING YOUR RIGHT TO A JURY TRIAL ON YOUR CLAIMS. PLEASE READ SECTION 15 CAREFULLY.

BY CLICKING ON THE “I ACCEPT” BUTTON, COMPLETING THE ACCOUNT REGISTRATION PROCESS, USING OUR SERVICES AND/OR PURCHASING DIGITAL ASSETS, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. If you do not agree to these Terms, you may not access or use the Service or purchase the Digital Assets.

JVC reserves the right to change or modify these Terms at any time and in our sole discretion. If we make changes to these Terms, we will provide notice of such changes, such as by sending an email notification, providing notice through the Service or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference. We encourage you to review the Terms frequently to ensure that you understand the terms and conditions that apply when you access or use the Service. If you do not agree to the revised Terms, you may not access or use the Service.
<br/>
2. What are the rules for using JNFT or the Service
•	When using JNFT, no User is allowed to:
	manipulate the price of a Digital Artwork in any way, including bidding on your own items, preventing bidding, or using JNFT to conceal economic activity.
	email or otherwise upload any content that (i) infringes any intellectual property or other proprietary rights of any party; (ii) you do not have a right to upload under any law or under contractual or fiduciary relationships; (iii) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; (iv) poses or creates a privacy or security risk to any person; (v) constitutes unsolicited or unauthorized advertising, promotional materials, commercial activities and/or sales, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” “contests,” “sweepstakes,” or any other form of solicitation; (vi) is unlawful, harmful, threatening, abusive, harassing, tortious, excessively violent, defamatory, vulgar, obscene, pornographic, libelous, invasive of another’s privacy, hateful racially, ethnically or otherwise objectionable; or (vii) in the sole judgment of JNFT, is objectionable or which restricts or inhibits any other person from using or enjoying the Platform, or which may expose JNFT or its users to any harm or liability of any type;
	interfere with or disrupt the Platform or servers or networks connected to the Platform, or disobey any requirements, procedures, policies or regulations of networks connected to the Platform ; or 
•	
•	
	violate any applicable local, state, national or international law, or any regulations having the force of law, including but not limited to the U.S. Department of Treasury’s Office of Foreign Assets Control (“OFAC”), or which would involve proceeds of any unlawful activity; 
	impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity;
	solicit personal information from anyone under the age of 18;
	harvest or collect email addresses or other contact information of other Users from the Platform by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;
	advertise or offer to sell or buy any goods or services for any business purpose that is not specifically authorized;
	further or promote any criminal activity or enterprise or provide instructional information about illegal activities, including for the purpose of concealing economic activity, laundering money, or financing terrorism; 
	obtain or attempt to access or otherwise obtain any materials or information through any means not intentionally made available or provided for through the Platform; 
	use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of the Platform or the content posted on the Platform, or to collect information about its Users for any unauthorized purpose;
	create user accounts by automated means or under false or fraudulent pretenses; 
	access or use the Platform for the purpose of creating a product or service that is competitive with any of our products or services.
<br/>
3. Privacy Policy
Please refer to our Privacy Policy for information about how we collect, use and share personal information about you.
<br/>
4. Account Registration and Communication Preferences
a.	If you wish to participate in an Auction for Digital Assets, you will need to register for an account on the Service (“Account”). By creating an Account, you agree to (a) provide accurate, current and complete Account information about yourself, (b) maintain and promptly update from time to time as necessary your Account information, (c) maintain the security of your password and accept all risks of unauthorized access to your Account and the information you provide to us, and (d) immediately notify us if you discover or otherwise suspect any security breaches related to the Service, or your Account. JVC will block multiple accounts of the same user. Also, you agree that you will not:
	create another account if we’ve disabled one you had unless you have our written permission first;
	buy, sell, rent or lease access to your Account or username unless you have our written permission first;
	share your Account password with anyone; or
	log in or try to log in to access the Service through unauthorized third party applications or clients.
b.	JVC may require you to provide additional information and documents at the request of any competent authority or in case of application of any applicable law or regulation, including laws related to anti-laundering (legalization) of incomes obtained by criminal means, or for counteracting financing of terrorism. JVC may also require you to provide additional information and documents in cases where it has reasons to believe that:
	Your Account is being used for money laundering or for any other illegal activity;
	You have concealed or reported false identification information and other details; or
	Transactions effected via your Account were effected in breach of these Terms.
In such cases, JVC, in its sole discretion, may pause or cancel your Auction transactions until such additional information and documents are reviewed by JVC and accepted as satisfying the requirements of applicable law. If you do not provide complete and accurate information and documents in response to such a request, JVC may refuse to provide the Content (defined in Section 4(A) below) to you.
c.	By creating an Account, you consent to receive electronic communications from JVC (e.g., via email or by posting notices to the Service). These communications may include notices about your Account (e.g., password changes and other transactional information) and are part of your relationship with us. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including, but not limited to, that such communications be in writing. You should maintain copies of electronic communications from us by printing a paper copy or saving an electronic copy. We may also send you promotional communications via email, including, but not limited to, newsletters, special offers, surveys and other news and information we think will be of interest to you. You may opt out of receiving these promotional emails at any time by following the unsubscribe instructions provided therein.
d.	By submitting personal data through our Site or Services, you agree to the terms of our Privacy Policy and you expressly consent to the collection, use and disclosure of your personal data in accordance with the Privacy Policy.
e.	You must provide all equipment and software necessary to connect to the Service and services, including but not limited to, a mobile device that is suitable to connect with and use Service and services, in cases where the Service offers a mobile component. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Service or services.
f.	Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by JVC or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components. For example, when you click to get more details about any of the Digital Assets sold through our marketplace, you will notice a third party link to the website from which such Crypto Asset originated. Such website may include license terms governing the use of such Crypto Asset. In the event you purchase such Crypto Asset through our marketplace, you are required to comply with such terms.
g.	As stated above, your participation in the Auction is also subject to the rules available on this page, Auction Rules.
<br/>
5. Ownership
a.     Unless otherwise indicated in writing by us, the Service and all content and other materials contained therein, including, without limitation, the JVC logo and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, “Content”) are the proprietary property of JVC or our affiliates, licensors or users, as applicable.
b.    Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by JVC or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components.
c.    The JVC logo and any JVC product or service names, logos or slogans that may appear on the Service or Service are trademarks of JVC or our affiliates and may not be copied, imitated or used, in whole or in part, without our prior written permission. You may not use any metatags or other “hidden text” utilizing “JVC” or any other name, trademark or product or service name of JVC or our affiliates without our prior written permission. In addition, the look and feel of the Service and Content, including, without limitation, all page headers, custom graphics, button icons and scripts, constitute the service mark, trademark or trade dress of JVC and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and JVC names or logos mentioned on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable trademark holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by JVC.
<br/>
6. License to Access and Use Our Service and Content
You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable, and personal license to access and use the Service and Content; provided, however, that such license is subject to these Terms and does not include any right to (a) sell, resell or use commercially the Service or Content, (b) distribute, publicly perform or publicly display any Content, (c) modify or otherwise make any derivative uses of the Service or Content, or any portion thereof, (d) use any data mining, robots or similar data gathering or extraction methods, (e) download (other than page caching) any portion of the Service or Content, except as expressly permitted by us, and (f) use the Service or Content other than for their intended purposes.
<br/>
7. Hyperlinks
You are granted a limited, nonexclusive, nontransferable right to create a text hyperlink to the Service for noncommercial purposes, provided that such link does not portray JVC or our affiliates or any of our products or services in a false, misleading, derogatory or otherwise defamatory manner, and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited right may be revoked at any time. You may not use a logo or other proprietary graphic of JVC to link to the Service or Content without our express written permission. Further, you may not use, frame or utilize framing techniques to enclose any JVC trademark, logo or other proprietary information, including the images found on the Service, the content of any text or the layout or design of any page, or form contained on a page, on the Service without our express written consent.
<br/>
8. Third Party Services
The Service may contain links to third-party websites (“Third-Party Websites”) and applications (“Third-Party Applications”). When you click on a link to a Third-Party Website or Third-Party Application, we will not warn you that you have left our Service and are subject to the Terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites and Third-Party Applications and are not under the control of JVC. JVC is not responsible for any Third-Party Websites or Third-Party Applications. JVC provides these Third-Party Websites and Third-Party Applications only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites or Third-Party Applications, or their products or services. You use all links in Third-Party Websites, and Third-Party Applications at your own risk. When you leave our Service, our Terms and policies no longer govern. You should review all applicable agreements and policies, including privacy and data gathering practices, of any Third-Party Websites or Third-Party Applications, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.
<br/>9. User Conduct
You agree that you will not violate any law, contract, intellectual property or other third party right, and that you are solely responsible for your conduct, while accessing or using the Service or participating in the Auction. You agree that you will abide by these Terms and will not:
	Provide false or misleading information to JVC;
	Use or attempt to use another user’s Account without authorization from such user and JVC;
	Create or list counterfeit items;
	Pose as another person or create a misleading username;
	Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service, or that could damage, disable, overburden or impair the functioning of the Service in any manner;
	Develop, utilize, or disseminate any software, or interact with any API in any manner, that could damage, harm, or impair the Service;
	Reverse engineer any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any Service, area or code of the Service;
	Attempt to circumvent any content-filtering techniques we employ, or attempt to access any feature or area of the Service that you are not authorized to access;
	Use any robot, spider, crawler, scraper, script, browser extension, offline reader or other automated means or interface not authorized by us to access the Service, extract data or otherwise interfere with or modify the rendering of Service pages or functionality;
	Use data collected from our Service to contact individuals, companies, or other persons or entities;
	Use data collected from our Service for any direct marketing activity (including without limitation, email marketing, SMS marketing, telemarketing, and direct marketing);
	Bypass or ignore instructions that control all automated access to the Service;
	Use the Service for any illegal or unauthorized purpose, or engage in, encourage or promote any activity that violates these Terms;
	Use the Platform to carry out any illegal activities, including but not limited to money laundering, terrorist financing or deliberately engaging in activities designed to adversely affect the performance of the Platform, or the Service;
	Engage in wash trading or other deceptive or manipulative trading activities;
	Place misleading bids or offers;
	Spam listings for the purpose of causing a listing to appear at the top of the search results;
	Engage in behaviors that have the intention or the effect of artificially increasing view counts, favorites, volume, or other metrics that JVC might use to sort search results;
	Use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, listing, or buying securities, commodities, options, real estate, or debt instruments;
	Use the Service from a country sanctioned by the government of the United States; or
	Use the Service to participate in fundraising for a business, protocol, or platform, including but not limited to creating, listing, or buying assets that are redeemable for financial instruments, assets that give owners rights to participate in an ICO or any securities offering, or assets that entitle owners to financial rewards, including but not limited to, DeFi yield bonuses, staking bonuses, and burn discounts.
JVC facilitates trade among a diverse community of buyers and sellers. Openness is one of our most prized values, and we&apos;re committed to providing a platform for the exchange of a wide range of content, including controversial content. These policies ensure that our marketplace offers the widest selection of assets possible while promoting trust and respect, as well as adherence to the law.
JVC has always exercised judgment in allowing or disallowing certain assets, listings, smart contracts, and collections consistent with the spirit of openness in a worldwide community of users of a radical new technology. We carefully consider the complete situation and all its details in light of our policies before deciding to remove inappropriate assets, listings, smart contracts, and collections when we discover them or they&apos;re brought to our attention.
Assets, listings, smart contracts, and collections that JVC deems inappropriate, disruptive, or illegal are prohibited on JVC. JVC reserves the rights to determine the appropriateness of listings on its site and remove any listing at any time. If you create or offer an asset, listing, smart contract, or collection in violation of these policies, we will take corrective actions, as appropriate, including but not limited to removing the asset, listing, smart contract, or collection, deleting your JVC account, and permanently withholding referral payments and developer revenue sharing fees. JVC cannot destroy or impound your assets or smart contracts, but we reserve the right to destroy inappropriate metadata stored on our servers.
Assets, listings, smart contracts, and collections that include metadata that violates international or Thai intellectual property laws, promotes suicide or self-harm, incites hate or violence against others, degrades or doxes another individual, depicts minors in sexually suggestive situations, or is otherwise illegal in the Kingdom of Thailand are prohibited on JNFT and will be removed.
Assets, listings, smart contracts, and collections with a primary or substantial purpose in a game or application that violates international or Thai intellectual property laws, promotes suicide or self-harm, incites hate or violence against others, degrades or doxes another individual, depicts minors in sexually suggestive situations, or is otherwise illegal in the Kingdom of Thailand are prohibited on JNFT and will be removed.
Assets, listings, smart contracts, and collections created or used primarily or substantially for the purpose of raising funds for the known terrorist organizations are prohibited on JNFT and will be removed.
The sale of stolen assets, converted assets, fraudulently obtained assets, assets taken without authorization, and other illegally obtained assets on JNFT is prohibited. Listing illegally obtained assets may result in your listings being cancelled, your assets being hidden, or your account being suspended.
If you have reason to believe that an asset listed on JNFT was illegally obtained, please contact us immediately at info@jventures.co.th. Include the asset&apos;s ID, the asset&apos;s contract address, and evidence demonstrating that the asset was illegally obtained. JVC will review your claim and reply within 72 hours. If we determine from the evidence that the asset is stolen, we will hide it or disable trading of it.
There is no minimum age requirement for all users to be in case of a Creator, and a complete 20 years old or older in case of a Collector. If you are under 20 years old in case of being a Collector or Bidder, you may use a parent or guardian&apos;s JNFT account, but only with involvement of the account holder. However, the account holder is responsible for everything done with that account.
Do not create or list illegal or offensive content, such as products that depict graphic sexual acts and images that depict children under the age of 18 in a sexually suggestive manner. Do not use profanity or graphic language in any content you list or create on JNFT.
If you become aware of the creation, listing, or buying of assets in violation of any of the terms specified in this section, you shall contact us here to report it. Creators bear special responsibility for informing JVC of the existence of their collections, contracts, and assets that violate these terms.
<br/>10. User Information, Intellectual Property Rights and Copyright
You are solely responsible for your use of the Services and for any User Information you provide, including compliance with applicable laws, rules, and regulations. We take no responsibility for the User Information posted or listed via the Services.
You retain your rights to any User Information you submit, post, or display using the Services.
By submitting, posting or displaying User Information on or through the Services, you grant us a worldwide, non-exclusive, sublicensable, royalty-free license to use, copy, modify, and display any text, content, files, communications, comments, feedback, suggestions, ideas, concepts, questions, data or other content that you submit or post on or through the Services or through tools or applications we provide for posting or sharing such content (collectively “User Information”) for our lawful business purposes, including to provide, promote, and improve the Services.
JVC does not claim that submitting, posting or displaying User Information on or through the Services gives JVC any ownership or resale rights in your User Information. We&apos;re not saying we own it or will resell it. We&apos;re just saying we might show it off a bit.
You represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power and/or authority necessary to grant the rights granted herein for any User Information that you submit, post or display on or through the Services. You agree that such User Information will not contain material subject to copyright or other proprietary rights, unless you have necessary permission or are otherwise legally entitled to post the material and to grant JVC the license described above.
JVC reserves the right to remove content without prior notice. JVC will take down works in response to formal infringement claims and will terminate a user&apos;s access to the Services if the user is determined to be a repeat infringer.
What are the intellectual property rights on the Platform?
Creator Rights
The Creator owns all legal right, title, and interest in all intellectual property rights underlying the Digital Artwork minted by the Creator on the Platform, including but not limited to copyrights and trademarks. As the copyright owner, the Creator has the right to reproduce, prepare derivative Digital Artwork, distribute, and display or perform the Digital Artwork. 
Creators hereby acknowledges, understands, and agrees that selling a Digital Artwork on JNFT constitutes an express representation, warranty, and covenant that the Creator has not, will not, and will not cause another to sell, tokenize, or create another cryptographic token representing a digital collectible for the same Digital Artwork, excepting, without limitation, the Creator’s ability to sell, tokenize, or create a cryptographic token or other digital asset representing a legal, economic, or other interest relating to any of the exclusive rights belonging to the Creator under copyright law.
The Creator hereby acknowledges, understands, and agrees that launching a Digital Artwork on JNFT constitutes an express and affirmative grant to JNFT, its affiliates and successors a non-exclusive, world-wide, assignable, sublicensable, perpetual, and royalty-free license to make copies of, display, perform, reproduce, and distribute the Digital Artwork on any media whether now known or later discovered for the broad purpose of operating, promoting, sharing, developing, marketing, and advertising the Platform, or any other purpose related to JNFT, including without limitation, the express right to: (i) display or perform the Digital Artwork on the Platform, a third party platform, social media posts, blogs, editorials, advertising, market reports, virtual galleries, museums, virtual environments, editorials, or to the public; (ii) create and distribute digital or physical derivative Digital Artwork based on the Digital Artwork; (iii) indexing the Digital Artwork in electronic databases, indexes, catalogues; and (iv) hosting, storing, distributing, and reproducing one or more copies of the Digital Artwork within a distributed file keeping system, node cluster, or other database (e.g., IPFS) or causing, directing, or soliciting others to do so.
Creators expressly represent and warrant that their Digital Artwork listed on JNFT contains only original content otherwise authorized for use by the Creator, and does not contain unlicensed or unauthorized copyrighted content, including any imagery, design, audio, video, human likeness, or other unoriginal content not created by the Creator, not authorized for use by the Creator, not in the public domain, or otherwise without a valid claim of fair use, the Creator further represents and warrants that it has permission to incorporate the unoriginal content. 
Collectors Rights
Collectors receive a cryptographic token representing the Creator’s Digital Artwork as a piece of property, but do not own the creative work itself. Collectors may display and share the Digital Artwork, but Collectors do not have any legal ownership, right, or title to any copyrights, trademarks, or other intellectual property rights to the Digital Artwork, excepting the limited license to the Digital Artwork granted by these Terms.  Upon collecting a Digital Artwork, Collectors receive a limited, worldwide, non-assignable, non-sublicensable, royalty-free license to display the Digital Artwork legally owned and properly obtained by the Collector.
The Collector’s limited license to display the Digital Artwork, includes, but is not limited to, the right to display the Digital Artwork privately or publicly: (i) for the purpose of promoting or sharing the Collector’s purchase, ownership, or interest, (ii) for the purpose of sharing, promoting, discussing, or commenting on the Digital Artwork; (iii) on third party marketplaces, exchanges, platforms, or applications in association with an offer to sell, or trade, the Digital Artwork; and (iv) within decentralized virtual environments, virtual worlds, virtual galleries, virtual museums, or other navigable and perceivable virtual environments.  
Collectors have the right to sell, trade, transfer, or use their Digital Artwork, but Collectors may not make “commercial use” of the Digital Artwork.  
The Collector agrees that it may not, nor permit any third party, to do or attempt to do any of the foregoing without the Creator’s express prior written consent in each case: (i) modify, distort, mutilate, or perform any other modification to the Work which would be prejudicial to the Creator’s honor or reputation; (ii) use the Digital Artwork to advertise, market, or sell any third party product or service; (iii) use the Digital Artwork in connection with images, videos, or other forms of media that depict hatred, intolerance, violence, cruelty, or anything else that could reasonably be found to constitute hate speech or otherwise infringe upon the rights of others; (iv) incorporate the Digital Artwork in movies, videos, video games, or any other forms of media for a commercial purpose, except to the limited extent that such use is expressly permitted by these Terms or solely for your Collector’s personal, non-commercial use; (v) sell, distribute for commercial gain, or otherwise commercialize merchandise that includes, contains, or consists of the Digital Artwork; (vi) attempt to trademark, copyright, or otherwise acquire additional intellectual property rights in or to the Digital Artwork; (vii) attempt to mint, tokenize, or create an additional cryptographic token representing the same Digital Artwork, whether on or off of the JNFT Platform; (viii) falsify, misrepresent, or conceal the authorship of the Digital Artwork; or (ix) otherwise utilize the Digital Artwork for the Collector’s or any third party’s commercial benefit.
Collectors irrevocably release, acquit, and forever discharge JNFT and its subsidiaries, affiliates, officers, and successors of any liability for direct or indirect copyright or trademark infringement for JNFT use of a Digital Artwork in accordance with these Terms.
Platform Content, Software and Trademarks: You acknowledge and agree that the Platform may contain content or features (“Platform Content”) that are protected by copyright, patent, trademark, trade secret or other proprietary rights and laws.  Except as expressly authorized by JNFT, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Platform or the Platform Content, in whole or in part.  In connection with your use of the Platform you will not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods.  If you are blocked by JNFT from accessing the Platform (including by blocking your IP address), you agree not to implement any measures to circumvent such blocking (e.g., by masking your IP address or using a proxy IP address).  Any use of the Platform or the Platform Content other than as specifically authorized herein is strictly prohibited.  The technology and software underlying the Platform or distributed in connection therewith are the property of JNFT, our affiliates and our partners (the “Software”).  You agree not to copy, modify, create a derivative work of, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, or otherwise transfer any right in the Software.  Any rights not expressly granted herein are reserved by JNFT.
The JNFT name and logos are trademarks and service marks of JNFT Labs, Inc. (collectively the “JNFT Trademarks”). Other company, product, and service names and logos used and displayed via the Platform may be trademarks or service marks of their respective owners who may or may not endorse or be affiliated with or connected to JNFT. Nothing in this Terms of Service or the Platform should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any of JNFT Trademarks displayed on the Platform, without our prior written permission in each instance. All goodwill generated from the use of JNFT Trademarks will inure to our exclusive benefit.
Third Party Material:  Under no circumstances will JNFT be liable in any way for any content or materials of any third parties (including users), including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any such content.  You acknowledge that JNFT does not pre-screen content, but that JNFT and its designees will have the right (but not the obligation) in their sole discretion to refuse or remove any content that is available via the Platform. Without limiting the foregoing, JNFT and its designees will have the right to remove any content that violates these Terms of Service or is deemed by Platform, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content and the purchase of any Digital Artwork, including any reliance on the accuracy, completeness, or usefulness of such content. 
User Content Transmitted Through the Platform:  With respect to the content, Digital Artwork, or other materials you upload through the Platform or share with other users or recipients (collectively, “User Content”), you represent and warrant that you own all right, title and interest in and to such User Content, including, without limitation, all copyrights and rights of publicity contained therein.  By uploading any User Content, you hereby grant and will grant JNFT and its affiliated companies a nonexclusive, worldwide, royalty free, fully paid up, transferable, sublicensable, perpetual, irrevocable license to copy, display, upload, perform, distribute, store, modify and otherwise use your User Content in connection with the operation of the Platform or the promotion, advertising or marketing thereof in any form, medium or technology now known or later developed.  
Any questions, comments, suggestions, ideas, feedback or other information about the Platform (“Submissions”), provided by you to JNFT are non-confidential and JNFT will be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.  
JNFT may preserve content and may also disclose content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce these Terms of Service; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of JNFT, its users and the public. You understand that the technical processing and transmission of the Platform, including your content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.
If you believe that your content has been copied in a way that constitutes copyright infringement, please report this by contacting our designated copyright legal representative at:
Aber Group Co., Ltd.
Address: 14 Soi Srinakarin 7, Srinakarin Road,. Haumak, Bangkapi, Bangkok, Thailand 10240
Email: info@aberlegal.com
Phone: +66(0)2 379 95629
Formal infringement claims regarding content on the Services must include:
	A written communication delivered to the agent designated above;
	A physical or electronic signature of someone authorized to act on behalf of the copyright owner;
	Identification of the copyrighted work(s) allegedly infringed;
	Identification of material claimed to be infringing, reasonably sufficient to permit Company to locate the material;
	Information reasonably sufficient to permit Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;
	A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law; and”
	A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the copyright owner.
If you believe that your likeness has been used in a way that violates your personality rights, please report this by contacting our designated personality rights legal representative at:
Aber Group Co., Ltd.
Address: 14 Soi Srinakarin 7, Srinakarin Road,. Haumak, Bangkapi, Bangkok, Thailand 10240
Email: info@aberlegal.com
Phone: +66(0)2 379 95629
Formal claims regarding content on the Services must include:
	A written communication delivered to the agent designated above;
	A physical or electronic signature of someone authorized to act on behalf of the person or the estate affected;
	Identification of material claimed to be violating, reasonably sufficient to permit Company to locate the material;
	Information reasonably sufficient to permit Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;
	A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the person or the estate affected, its agent or the law; and”
	A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the person or the estate.
<br/>11. Fees and charges
What fees does JNFT charge?
Auction.  The terms and mechanics of the Auctions are set forth in our Help Center and incorporated into these Terms.  
•	Fees.  The Fees for an initial sale of Digital Artwork on JNFT is as follows:
	Creators receive 85% of the total sale price of an Initial Sale.
	JNFT collects 15% of the total sale price of an Initial Sale.
	You agree and understand that all fees, commissions, and royalties are transferred, processed, or initiated directly through one or more of the smart contracts on the Binance Smart Chain network. 
	The Fees for a secondary sale of Digital Artwork on JNFT is as follows:
	Seller receives 85% of the total sale price of a Secondary Sale.
	Original Creator receives 10% of the total sale price of a Secondary Sale.
	JNFT collects 5% of the total sale price of a Secondary Sale.
	You agree and understand that all fees, commissions, and royalties are transferred, processed, or initiated directly through one or more of the smart contracts on the Binance Smart Chain network.
JNFT does not generally collect any fees, commissions, or royalties for transactions occurring outside of JNFT. Users irrevocably releases, acquits, and forever discharges JNFT and its subsidiaries, affiliates, officers, and successors of any liability for royalties, fines, or fees not received from any off-market transaction.
All transactions on JNFT, including without limitation minting, tokenizing, bidding, listing, offering, purchasing, or confirming, are facilitated by smart contracts existing on the Binance Smart Chain network. The Binance Smart Chain network requires the payment of a transaction fee (a “Gas fee”) for every transaction that occurs on the Binance Smart Chain network, and thus every transaction occurring on JNFT. The value of the Gas Fee changes, often unpredictably, and is entirely outside of the control of JNFT. The User acknowledges that under no circumstances will a contract, agreement, offer, sale, bid, or other transaction on JNFT be invalidated, revocable, retractable, or otherwise unenforceable on the basis that the Gas Fee for the given transaction was unknown, too high, or otherwise unacceptable.
Taxes.  Users are responsible to pay any and all sales, use, value-added and other taxes, duties, and assessments now or hereafter claimed or imposed by any governmental authority, “associated with your use of JNFT (including, without limitation, any taxes that may become payable as the result of your ownership, transfer, purchase, sale, or creation of any artworks).
Beta Platforms.  Certain features on JNFT may be offered while still in “beta” form (“Beta Platforms”). JNFT will utilize best efforts to identify the Beta Platforms by labeling on its Platform. By accepting these Terms or using the Beta Platforms, you understand and acknowledge that the Beta Platforms are being provided as a “Beta” version and made available on an “As Is” or “As Available” basis. The Beta Platforms may contain bugs, errors, and other problems. YOU ASSUME ALL RISKS AND ALL COSTS ASSOCIATED WITH YOUR USE OF THE BETA PLATFORMS, INCLUDING, WITHOUT LIMITATION, ANY INTERNET ACCESS FEES, BACK-UP EXPENSES, COSTS INCURRED FOR THE USE OF YOUR DEVICE AND PERIPHERALS, AND ANY DAMAGE TO ANY EQUIPMENT, SOFTWARE, INFORMATION OR DATA. In addition, we are not obligated to provide any maintenance, technical, or other support for the Beta Platforms.
<br/>12. Indemnification
To the fullest extent permitted by applicable law, you agree to indemnify, defend and hold harmless JVC, and our respective past, present and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors and assigns (individually and collectively, the “JVC Parties”), from and against all actual or alleged third party claims, damages, awards, judgments, losses, liabilities, obligations, penalties, interest, fees, expenses (including, without limitation, attorneys’ fees and expenses) and costs (including, without limitation, court costs, costs of settlement and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract or otherwise (collectively, “Claims”), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to (a) your use or misuse of the Service, User Information or Digital Assets, (b) any feedback you provide, (c) your violation of these Terms, and (d) your violation of the rights of a third party, including another user or MetaMask. You agree to promptly notify JVC of any third party Claims and cooperate with the JVC Parties in defending such Claims. You further agree that the JVC Parties shall have control of the defense or settlement of any third party Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND JVC.
<br/>13. Disclaimers
EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY JVC, THE SERVICE, CONTENT CONTAINED THEREIN, AND DIGITAL ASSETS LISTED THEREIN ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. JVC (AND ITS SUPPLIERS) MAKE NO WARRANTY THAT THE SERVICE: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE. JVC DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SERVICE, CONTENT CONTAINED THEREIN. JVC DOES NOT REPRESENT OR WARRANT THAT CONTENT ON THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WE WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE SERVICE. WHILE JVC ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE AND CONTENT SAFE, JVC CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, ANY DIGITAL ASSETS LISTED ON OUR SERVICE OR OUR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.
WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF DIGITAL ASSETS, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (A) USER ERROR SUCH AS FORGOTTEN PASSWORDS, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; (B) SERVER FAILURE OR DATA LOSS; (C) CORRUPTED WALLET FILES; (D) UNAUTHORIZED ACCESS TO APPLICATIONS; (E) ANY UNAUTHORIZED THIRD PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR DIGITAL ASSETS.
DIGITAL ASSETS ARE INTANGIBLE DIGITAL ASSETS. THEY EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE BINANCE SMART CHAIN NETWORK. ANY TRANSFER OF TITLE THAT MIGHT OCCUR IN ANY UNIQUE DIGITAL ASSET OCCURS ON THE DECENTRALIZED LEDGER WITHIN THE  PLATFORM. WE DO NOT GUARANTEE THAT JVC OR ANY JVC PARTY CAN EFFECT THE TRANSFER OF TITLE OR RIGHT IN ANY DIGITAL ASSETS.
JVC is not responsible for sustained casualties due to vulnerability or any kind of failure, abnormal behavior of software (e.g., wallet, smart contract), blockchains or any other features of the Digital Assets. JVC is not responsible for casualties due to late report by developers or representatives (or no report at all) of any issues with the blockchain supporting Digital Assets including forks, technical node issues or any other issues having fund losses as a result.
JVC is not responsible for any infringement arising out of KYC verified users’s trading within the platform, the platform acts as a free marketplace for buyers and sellers. Therefore, JVC and the platform shall not be held accountable for any fradulent acts committed between the users.
Nothing in these Terms shall exclude or limit liability of either party for fraud, death or bodily injury caused by negligence, violation of laws, or any other activity that cannot be limited or excluded by legitimate means.
SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.
<br/>14. Assumption of Risk
You accept and acknowledge:
a.	The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the Digital Assets, which may also be subject to significant price volatility. We cannot guarantee that any purchasers of Digital Assets will not lose money.
b.	You are solely responsible for determining what, if any, taxes apply to your Digital Assets transactions. Neither JVC nor any other JVC Party is responsible for determining the taxes that apply to Digital Assets transactions.
c.	Our Service does not store, send, or receive Digital Assets. This is because Digital Assets exist only by virtue of the ownership record maintained on its supporting blockchain. Any transfer of Digital Assets occurs within the supporting blockchain and not on this Service.
d.	There are risks associated with using an Internet based currency, including but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet. You accept and acknowledge that JVC will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Digital Assets, however caused.
e.	A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications, and could therefore also negatively impact the potential utility or value of Digital Assets.
f.	The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Auction and/or Service and the utility of Digital Assets.
g.	The Service will rely on third-party platforms such as MetaMask to perform the transactions for the Auction of Digital Assets. If we are unable to maintain a good relationship with such platform providers; if the terms and conditions or pricing of such platform providers change; if we violate or cannot comply with the terms and conditions of such platforms; or if any of such platforms loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Service will suffer.
h.	There are risks associated with purchasing user generated content, including but not limited to, the risk of purchasing counterfeit assets, mislabeled assets, assets that are vulnerable to metadata decay, assets on smart contracts with bugs, and assets that may become untransferable. JVC reserves the right to hide collections, contracts, and assets affected by any of these issues or by other issues. Assets you purchase may become inaccessible on JVC. Under no circumstances shall the inability to view your assets on JVC serve as grounds for a claim against JVC.
<br/>15. Limitation of Liability
TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL JVC BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM THESE TERMS, THE SERVICE, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF JVC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SERVICES, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.
NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF JVC ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, DIGITAL ASSETS, OR ANY PRODUCTS OR SERVICES PURCHASED ON THE SERVICE EXCEED THE GREATER OF (A) $100 OR (B) THE AMOUNT RECEIVED BY JVC FROM THE SALE OF DIGITAL ASSETS THAT ARE THE SUBJECT OF THE CLAIM.
THE FOREGOING LIMITATIONS OF LIABILITY SHALL NOT APPLY TO LIABILITY OF JVC FOR (A) DEATH OR PERSONAL INJURY CAUSED BY A MEMBER OF JVC’S NEGLIGENCE; OR FOR (B) ANY INJURY CAUSED BY A MEMBER OF JVC’S FRAUD OR FRAUDULENT MISREPRESENTATION
Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.
<br/>16. Modifications to the Service
We reserve the right in our sole discretion to modify, suspend or discontinue, temporarily or permanently, the Services (or any features or parts thereof) or suspend or discontinue the Auction at any time and without liability therefore.
<br/>17. Dispute Resolution; Arbitration.
a.	Dispute Resolution. Please read the following arbitration agreement in this Section (“Arbitration Agreement”) carefully. It requires you to arbitrate disputes with JVC and limits the manner in which you can seek relief from us.
b.	Applicability of Arbitration Agreement. You agree that any dispute or claim relating in any way to your access or use of the Service, to any products sold or distributed through the Service, or to any aspect of your relationship with JVC, will be resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify; and (2) you or JVC may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents).
c.	Arbitration Rules and Forum. The Thai Arbitration Act B.E. 2545 governs the interpretation and enforcement of this Arbitration Agreement. To begin an arbitration proceeding, you must send a letter requesting arbitration and describing your claim to our registered agent Aber Group, 14 Soi Srinakarin 7, Srinakarin Road, Haumak, Bangkapi, Bangkok, Thailand 10240. The arbitration will be conducted by THAC, an established alternative dispute resolution provider. Disputes involving claims and counterclaims of capital under 2,500,000 Baht or US $ 77,750 equivalent can be proceeded at the minimum rate of 50,000 Baht or US $ 1550 equivalent for THAC fee, and at the minimum rate of 150,000 Baht or US $ 4,670 equivalent for per person arbitrator’s fee, not inclusive of attorneys’ fees and interest, shall be subject to THAC’s most current version of the Arbitration cost, rules and procedures available at https://thac.or.th/arbitration/; all other claims shall be subject to THAC’s most current version of the Comprehensive Arbitration Rules and Procedures, available at https://thac.or.th/arbitration/. THAC’s rules and Arbitrator’s lists are also available at https://thac.or.th/wp-content/uploads/2020/09/THAC-Arbitration-Rules.pdf and https://thac.or.th/panelists/ respectively, or by emailing at info@thac.or.th, or calling THAC at +66(0)2018 1615. If THAC is not available to arbitrate, the parties will select an alternative arbitral forum. The arbitrator may dismiss the case if the arbitrator finds that you cannot afford to pay THAC’s filing, administrative, hearing and/or other fees and cannot obtain a waiver from THAC. In addition, JVC will reimburse all such THAC’s filing, administrative, hearing and/or other fees for claims totaling less than $10,000 only if the case was ruled in your favor unless the arbitrator determines the claims are frivolous. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the country where you live or at another mutually agreed location. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.
d.	Authority of Arbitrator. The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of you and JVC. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non- monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and the Terms (including the Arbitration Agreement). The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.
e.	Waiver of Jury Trial. YOU AND JVC HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. You and JVC are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in Section 15(b) above. An arbitrator can award on an individual basis the same damages and relief as a court and must follow these Terms as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.
f.	Waiver of Class or Other Non-Individualized Relief. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A OR COLLECTIVE CLASS BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If a decision is issued stating that applicable law precludes enforcement of any part of this subsection’s limitations as to a given claim for relief, then that claim must be severed from the arbitration and brought in Thai courts located within the Kingdom of Thailand. All other claims shall be arbitrated.
g.	30-Day Right to Opt Out. You have the right to opt out of the provisions of this Arbitration Agreement by sending written notice of your decision to opt out to the following address: J Ventures Co., Ltd.,191 Jaymart Building, Ramkamhaeng Road, Rat Phatthana, Saphan Sung, Bangkok, Thailand 10240, within 30 days after first becoming subject to this Arbitration Agreement. You may also submit your decision here. Your notice must include your name and address, the email address you used to set up your account (if you have one), and an unequivocal statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of these Terms will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may currently have, or may enter in the future, with us.
h.	Severability. Except as provided in this Section, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Arbitration Agreement shall continue in full force and effect.
i.	Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with JVC.
j.	Modification. Notwithstanding any provision in these Terms to the contrary, we agree that if JVC makes any future material change to this Arbitration Agreement, you may reject that change within thirty (30) days of such change becoming effective by writing to JVC at the following address: 191 Jaymart Building, Ramkamhaeng Road, Rat Phatthana, Saphan Sung, Bangkok, Thailand 10240
By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this Arbitration Agreement as of the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service).
<br/>18. Governing Law and Venue
These Terms, your access to and use of the Service and Content, and your participation in the Auction shall be governed by and construed and enforced in accordance with the laws of the Kingdom of Thailand, without regard to conflict of law, rules, or principles of the Kingdom of Thailand, or any other jurisdiction that would cause the application of the laws. Any dispute between the parties that is not subject to arbitration or cannot be heard in small claims court, shall be resolved in the Civil Court, sitting within the Kingdom of Thailand.
<br/>19. Termination
You agree that JVC, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the Platform and remove and discard any content within the Platform, for any reason, including, without limitation, for lack of use or if JVC believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Service. Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Platform, may be referred to appropriate law enforcement authorities. JVC may also in its sole discretion and at any time discontinue providing the Platform, or any part thereof, with or without notice. You agree that any termination of your access to the Platform under any provision of this Terms of Service may be effected without prior notice, and acknowledge and agree that JVC may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Platform. Further, you agree that JVC will not be liable to you or any third party for any termination of your access to the Platform or to refund of any amounts that you have already paid to us, to the fullest extent permitted by applicable law.
We do not get involved with User disputes.  
You agree that you are solely responsible for your interactions with any other Users in connection with the Platform and JVC will have no liability or responsibility with respect thereto. JVC reserves the right, but has no obligation, to become involved in any way with disputes between you and any other user of the Platform.
<br/>20. Severability
If any term, clause or provision of these Terms is held invalid or unenforceable, then that term, clause or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause or provision, or any other term, clause or provision of these Terms.
<br/>21. Survival
The following sections will survive the expiration or termination of these Terms and the termination of your Account: all defined terms and Sections 1-4 and 7-19.
<br/>22. Miscellaneous
These Terms along with the Auction Rules constitute the entire agreement between you and JVC relating to your access to and use of the Services and Content, and your participation in the Auction. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of JVC prior, concurrent or subsequent circumstance, and JVC’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Except as otherwise provided herein, these Terms is intended solely for the benefit of the parties and are not intended to confer third party beneficiary rights upon any other person or entity.
<br/>
Measures for collecting, using or disclosing personal information including storage and destroy the company&apos;s personal data. You can read at https://www.jventures.co.th/terms
					</div>
				</div>
				<div className="col-12 col-lg-7 my-4">
					<Form>
						<div className="mb-3 layout-radio_reg">
							<label className="ci-bg-orange-V1 form-control">
								<input
									type="radio"
									name="subject"
									label="ฉันยอมรับเงื่อนไขข้อตกลง"
									checked={policy && policy !== null}
									onChange={() => handleChangePolicy(true)}
									value="true"
								/>{" "}
								<span className="ci-color-black-V1 text-detail_radio">ฉันยอมรับเงื่อนไขข้อตกลง</span>
							</label>
							{/* <label className="ci-color-black-V1 ms-3">
								<input
									type="radio"
									name="subject"
									label="ไม่ยอมรับ"
									checked={!policy && policy !== null}
									onChange={() => handleChangePolicy(false)}
									value="false"
								/>{" "}
								ไม่ยอมรับ
							</label> */}
						</div>
						<div className="row ">
							<div className="col-md-4 col-12 mb-md-0 mb-3">
								<Link href="/">
									<button className="btn-cancel w-100 btn">ยกเลิก</button>
								</Link>
							</div>
							<div className="col-md-8 col-12">
								{policy ? (
									<Link href="/register/approve">
										<button className="btn-save w-100 btn">ถัดไป</button>
									</Link>
								) : (
									<button className="btn-save w-100 btn" disabled={!policy || policy == null}>
										ถัดไป
									</button>
								)}
							</div>
						</div>
					</Form>
				</div>
			</div>
		</section>
	);
};

export default Policy;
