export const NFTAbi = [
  {
    type: "event",
    name: "AddCollection",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "collectionId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "string",
        name: "name",
        internalType: "string",
        indexed: false,
      },
      {
        type: "string",
        name: "description",
        internalType: "string",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ApprovalForAll",
    inputs: [
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "operator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "bool",
        name: "approved",
        internalType: "bool",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GrantCreator",
    inputs: [
      {
        type: "address",
        name: "admin",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "user",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        type: "uint8",
        name: "version",
        internalType: "uint8",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Mint",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "tokenId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256",
        name: "collectionId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "loyaltyFeePercent",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MintBatch",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256[]",
        name: "tokenIds",
        internalType: "uint256[]",
        indexed: false,
      },
      {
        type: "uint256",
        name: "collectionId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256[]",
        name: "amounts",
        internalType: "uint256[]",
        indexed: false,
      },
      {
        type: "uint256",
        name: "loyaltyFeePercent",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MintBatchWithExtraInfo",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "receiver",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256[]",
        name: "tokenIds",
        internalType: "uint256[]",
        indexed: false,
      },
      {
        type: "uint256",
        name: "collectionId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256[]",
        name: "amounts",
        internalType: "uint256[]",
        indexed: false,
      },
      {
        type: "uint256",
        name: "loyaltyFeePercent",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MintWithExtraInfo",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "receiver",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "tokenId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "collectionId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "loyaltyFeePercent",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MoveTokenToCollection",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "tokenId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "uint256",
        name: "oldCollectionId",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "newCollectionId",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RevokeCreator",
    inputs: [
      {
        type: "address",
        name: "admin",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "user",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      {
        type: "bytes32",
        name: "role",
        internalType: "bytes32",
        indexed: true,
      },
      {
        type: "bytes32",
        name: "previousAdminRole",
        internalType: "bytes32",
        indexed: true,
      },
      {
        type: "bytes32",
        name: "newAdminRole",
        internalType: "bytes32",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      {
        type: "bytes32",
        name: "role",
        internalType: "bytes32",
        indexed: true,
      },
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "sender",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      {
        type: "bytes32",
        name: "role",
        internalType: "bytes32",
        indexed: true,
      },
      {
        type: "address",
        name: "account",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "sender",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferBatch",
    inputs: [
      {
        type: "address",
        name: "operator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "to",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256[]",
        name: "ids",
        internalType: "uint256[]",
        indexed: false,
      },
      {
        type: "uint256[]",
        name: "values",
        internalType: "uint256[]",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferSingle",
    inputs: [
      {
        type: "address",
        name: "operator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "from",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "to",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "id",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "value",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "URI",
    inputs: [
      {
        type: "string",
        name: "value",
        internalType: "string",
        indexed: false,
      },
      {
        type: "uint256",
        name: "id",
        internalType: "uint256",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateCollection",
    inputs: [
      {
        type: "address",
        name: "creator",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "collectionId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "string",
        name: "name",
        internalType: "string",
        indexed: false,
      },
      {
        type: "string",
        name: "description",
        internalType: "string",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "CREATOR_ROLE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "FEE_PERCENT_PRECISION",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "MAINTAINER_ROLE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "MAX_LOYALTY_FEE_PERCENT",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
    ],
    name: "addCollection",
    inputs: [
      { type: "string", name: "_name", internalType: "string" },
      { type: "string", name: "_description", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "balanceOf",
    inputs: [
      { type: "address", name: "account", internalType: "address" },
      { type: "uint256", name: "id", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "balanceOfBatch",
    inputs: [
      { type: "address[]", name: "accounts", internalType: "address[]" },
      { type: "uint256[]", name: "ids", internalType: "uint256[]" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "_feeAmount", internalType: "uint256" }],
    name: "calculateRoyaltyFee",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "collectionId", internalType: "uint256" },
      { type: "address", name: "owner", internalType: "address" },
      { type: "string", name: "name", internalType: "string" },
      { type: "string", name: "description", internalType: "string" },
    ],
    name: "collectionMap",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "collections",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "creationsOf",
    inputs: [{ type: "address", name: "_creator", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256[]", name: "", internalType: "uint256[]" }],
    name: "creationsOf",
    inputs: [
      { type: "address", name: "_creator", internalType: "address" },
      { type: "uint256", name: "_page", internalType: "uint256" },
      { type: "uint256", name: "_limit", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "creatorOf",
    inputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "creators",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "currentTokenId",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "exists",
    inputs: [{ type: "uint256", name: "id", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "launchTime", internalType: "uint256" },
      { type: "uint256", name: "launchPrice", internalType: "uint256" },
      { type: "uint256", name: "apr", internalType: "uint256" },
      { type: "uint256", name: "rarity", internalType: "uint256" },
    ],
    name: "extraInfo",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct ExtraInfos.ExtraInfoV2",
        components: [
          { type: "uint32", name: "value1", internalType: "uint32" },
          { type: "uint32", name: "value2", internalType: "uint32" },
          { type: "uint32", name: "value3", internalType: "uint32" },
          { type: "uint32", name: "value4", internalType: "uint32" },
          { type: "uint32", name: "value5", internalType: "uint32" },
          { type: "uint32", name: "value6", internalType: "uint32" },
          { type: "uint32", name: "value7", internalType: "uint32" },
          { type: "uint32", name: "value8", internalType: "uint32" },
          { type: "uint32", name: "value9", internalType: "uint32" },
          { type: "uint32", name: "value10", internalType: "uint32" },
        ],
      },
    ],
    name: "extraInfoOf",
    inputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint32", name: "value1", internalType: "uint32" },
      { type: "uint32", name: "value2", internalType: "uint32" },
      { type: "uint32", name: "value3", internalType: "uint32" },
      { type: "uint32", name: "value4", internalType: "uint32" },
      { type: "uint32", name: "value5", internalType: "uint32" },
      { type: "uint32", name: "value6", internalType: "uint32" },
      { type: "uint32", name: "value7", internalType: "uint32" },
      { type: "uint32", name: "value8", internalType: "uint32" },
      { type: "uint32", name: "value9", internalType: "uint32" },
      { type: "uint32", name: "value10", internalType: "uint32" },
    ],
    name: "extraInfoV2",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "getRoleAdmin",
    inputs: [{ type: "bytes32", name: "role", internalType: "bytes32" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint32", name: "", internalType: "uint32" }],
    name: "getValue",
    inputs: [
      { type: "uint256", name: "_index", internalType: "uint256" },
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "grantCreator",
    inputs: [{ type: "address", name: "_creator", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "grantMaintainer",
    inputs: [{ type: "address", name: "_maintainer", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "grantRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "hasRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "initialize",
    inputs: [
      { type: "address", name: "_admin", internalType: "address" },
      { type: "string", name: "_uri", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isApprovedForAll",
    inputs: [
      { type: "address", name: "account", internalType: "address" },
      { type: "address", name: "operator", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isCreator",
    inputs: [{ type: "address", name: "_user", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isMaintainer",
    inputs: [{ type: "address", name: "_user", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "loyaltyFeePercent",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "loyaltyFeePercentOf",
    inputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
    name: "mint",
    inputs: [
      {
        type: "uint256",
        name: "_loyaltyFeePercent",
        internalType: "uint256",
      },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256[]", name: "_tokenIds", internalType: "uint256[]" },
    ],
    name: "mintBatch",
    inputs: [
      {
        type: "uint256",
        name: "_loyaltyFeePercent",
        internalType: "uint256",
      },
      { type: "uint256[]", name: "_amounts", internalType: "uint256[]" },
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [
      { type: "uint256[]", name: "_tokenIds", internalType: "uint256[]" },
    ],
    name: "mintBatchWithExtraInfo",
    inputs: [
      { type: "address", name: "_creator", internalType: "address" },
      { type: "address", name: "_receiver", internalType: "address" },
      {
        type: "uint256",
        name: "_loyaltyFeePercent",
        internalType: "uint256",
      },
      { type: "uint256[]", name: "_amounts", internalType: "uint256[]" },
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
      {
        type: "tuple",
        name: "_params",
        internalType: "struct ExtraInfos.ExtraInfoParams",
        components: [
          { type: "uint32[]", name: "values1", internalType: "uint32[]" },
          { type: "uint32[]", name: "values2", internalType: "uint32[]" },
          { type: "uint32[]", name: "values3", internalType: "uint32[]" },
          { type: "uint32[]", name: "values4", internalType: "uint32[]" },
          { type: "uint32[]", name: "values5", internalType: "uint32[]" },
          { type: "uint32[]", name: "values6", internalType: "uint32[]" },
          { type: "uint32[]", name: "values7", internalType: "uint32[]" },
          { type: "uint32[]", name: "values8", internalType: "uint32[]" },
          { type: "uint32[]", name: "values9", internalType: "uint32[]" },
          { type: "uint32[]", name: "values10", internalType: "uint32[]" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
    name: "mintDelegate",
    inputs: [
      { type: "address", name: "_creator", internalType: "address" },
      {
        type: "uint256",
        name: "_loyaltyFeePercent",
        internalType: "uint256",
      },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
    name: "mintWithExtraInfo",
    inputs: [
      { type: "address", name: "_creator", internalType: "address" },
      { type: "address", name: "_receiver", internalType: "address" },
      {
        type: "uint256",
        name: "_loyaltyFeePercent",
        internalType: "uint256",
      },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
      {
        type: "tuple",
        name: "_extraInfo",
        internalType: "struct ExtraInfos.ExtraInfoV2",
        components: [
          { type: "uint32", name: "value1", internalType: "uint32" },
          { type: "uint32", name: "value2", internalType: "uint32" },
          { type: "uint32", name: "value3", internalType: "uint32" },
          { type: "uint32", name: "value4", internalType: "uint32" },
          { type: "uint32", name: "value5", internalType: "uint32" },
          { type: "uint32", name: "value6", internalType: "uint32" },
          { type: "uint32", name: "value7", internalType: "uint32" },
          { type: "uint32", name: "value8", internalType: "uint32" },
          { type: "uint32", name: "value9", internalType: "uint32" },
          { type: "uint32", name: "value10", internalType: "uint32" },
        ],
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "moveTokenToCollection",
    inputs: [
      { type: "uint256", name: "_tokenId", internalType: "uint256" },
      {
        type: "uint256",
        name: "_newCollectionId",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "pure",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "name",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "revokeCreator",
    inputs: [{ type: "address", name: "_creator", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "revokeMaintainer",
    inputs: [{ type: "address", name: "_maintainer", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "revokeRole",
    inputs: [
      { type: "bytes32", name: "role", internalType: "bytes32" },
      { type: "address", name: "account", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "safeBatchTransferFrom",
    inputs: [
      { type: "address", name: "from", internalType: "address" },
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256[]", name: "ids", internalType: "uint256[]" },
      { type: "uint256[]", name: "amounts", internalType: "uint256[]" },
      { type: "bytes", name: "data", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "safeTransferFrom",
    inputs: [
      { type: "address", name: "from", internalType: "address" },
      { type: "address", name: "to", internalType: "address" },
      { type: "uint256", name: "id", internalType: "uint256" },
      { type: "uint256", name: "amount", internalType: "uint256" },
      { type: "bytes", name: "data", internalType: "bytes" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setApprovalForAll",
    inputs: [
      { type: "address", name: "operator", internalType: "address" },
      { type: "bool", name: "approved", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setURI",
    inputs: [{ type: "string", name: "newuri", internalType: "string" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "supportsInterface",
    inputs: [{ type: "bytes4", name: "interfaceId", internalType: "bytes4" }],
  },
  {
    type: "function",
    stateMutability: "pure",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "symbol",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "totalSupply",
    inputs: [{ type: "uint256", name: "id", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "updateCollection",
    inputs: [
      { type: "uint256", name: "_collectionId", internalType: "uint256" },
      { type: "string", name: "_name", internalType: "string" },
      { type: "string", name: "_description", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "uri",
    inputs: [{ type: "uint256", name: "_tokenId", internalType: "uint256" }],
  },
];
